# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './bin/UI/ventana_madre.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cuadroBuscar = QtWidgets.QLineEdit(self.widget1)
        self.cuadroBuscar.setObjectName("cuadroBuscar")
        self.horizontalLayout.addWidget(self.cuadroBuscar)
        self.buscarButton = QtWidgets.QPushButton(self.widget1)
        self.buscarButton.setObjectName("buscarButton")
        self.horizontalLayout.addWidget(self.buscarButton)
        self.verticalLayout_2.addWidget(self.widget1)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonTitulosRegistrados = QtWidgets.QPushButton(self.widget_2)
        self.buttonTitulosRegistrados.setObjectName("buttonTitulosRegistrados")
        self.horizontalLayout_2.addWidget(self.buttonTitulosRegistrados)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.agregarButton = QtWidgets.QPushButton(self.widget_2)
        self.agregarButton.setObjectName("agregarButton")
        self.horizontalLayout_2.addWidget(self.agregarButton)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.widget)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.contadorLabel = QtWidgets.QLabel(self.widget_3)
        self.contadorLabel.setText("")
        self.contadorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.contadorLabel.setObjectName("contadorLabel")
        self.horizontalLayout_3.addWidget(self.contadorLabel)
        self.verticalLayout.addWidget(self.widget_3)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setStyleSheet("QTableWidget::item{\n"
"    border: None;\n"
"    padding-left: 10%;\n"
"    padding-right: 10%;\n"
"}")
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(180)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidget)
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.buttonEliminarRegistro = QtWidgets.QPushButton(self.widget_4)
        self.buttonEliminarRegistro.setObjectName("buttonEliminarRegistro")
        self.horizontalLayout_4.addWidget(self.buttonEliminarRegistro)
        self.verticalLayout.addWidget(self.widget_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuBase = QtWidgets.QMenu(self.menubar)
        self.menuBase.setObjectName("menuBase")
        self.menuEditar = QtWidgets.QMenu(self.menubar)
        self.menuEditar.setObjectName("menuEditar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionActualizarBase = QtWidgets.QAction(MainWindow)
        self.actionActualizarBase.setObjectName("actionActualizarBase")
        self.actionEditarRutaBase = QtWidgets.QAction(MainWindow)
        self.actionEditarRutaBase.setObjectName("actionEditarRutaBase")
        self.actionDeshacer = QtWidgets.QAction(MainWindow)
        self.actionDeshacer.setObjectName("actionDeshacer")
        self.actionRehacer = QtWidgets.QAction(MainWindow)
        self.actionRehacer.setObjectName("actionRehacer")
        self.actionExportarTXT = QtWidgets.QAction(MainWindow)
        self.actionExportarTXT.setObjectName("actionExportarTXT")
        self.actionImportarTXT = QtWidgets.QAction(MainWindow)
        self.actionImportarTXT.setObjectName("actionImportarTXT")
        self.menuBase.addAction(self.actionActualizarBase)
        self.menuBase.addAction(self.actionEditarRutaBase)
        self.menuEditar.addAction(self.actionDeshacer)
        self.menuEditar.addAction(self.actionRehacer)
        self.menuArchivo.addAction(self.actionExportarTXT)
        self.menuArchivo.addAction(self.actionImportarTXT)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuEditar.menuAction())
        self.menubar.addAction(self.menuBase.menuAction())
        self.label.setBuddy(self.cuadroBuscar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bitácora de lectura"))
        self.label.setText(_translate("MainWindow", "Buscar por título: "))
        self.buscarButton.setText(_translate("MainWindow", "Buscar"))
        self.buttonTitulosRegistrados.setText(_translate("MainWindow", "Ver/Editar títulos registrados"))
        self.agregarButton.setText(_translate("MainWindow", "Agregar registro"))
        self.label_2.setText(_translate("MainWindow", "Resultados de la búsqueda:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Título"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Fecha"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Hora"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Último leído"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.buttonEliminarRegistro.setToolTip(_translate("MainWindow", "<html><head/><body><p>Elimina el registro seleccionado</p></body></html>"))
        self.buttonEliminarRegistro.setText(_translate("MainWindow", "Eliminar registro"))
        self.menuBase.setTitle(_translate("MainWindow", "Base de datos"))
        self.menuEditar.setTitle(_translate("MainWindow", "Editar"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.actionActualizarBase.setText(_translate("MainWindow", "Actualizar"))
        self.actionEditarRutaBase.setText(_translate("MainWindow", "Editar ruta "))
        self.actionDeshacer.setText(_translate("MainWindow", "Deshacer"))
        self.actionRehacer.setText(_translate("MainWindow", "Rehacer"))
        self.actionExportarTXT.setText(_translate("MainWindow", "Exportar a TXT"))
        self.actionImportarTXT.setText(_translate("MainWindow", "Importar de TXT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
